### PR TITLE
Add prettier and husky to execute prettier on commit

### PR DESCRIPTION
**Pull request by aralroca**
Closes https://github.com/KovDimaY/React-Highcharts/issues/73

What I did:

- **Install prettier**.
- **Install husky**.
- **Write a husky hook to execute prettier on commit**.
- **Update Node from 8 to 10.13.0**. Husky requires Node 10. And prettier 10.13.0

Example of commit I did in my forked repo:

image

Happy hacktoberfest @KovDimaY

### CODE REVIEW

**Comment by aralroca** [comment]
I think it can also be interesting to add two npm scripts to format  and lint the staged files + to format / lint all of them. I will add them.

**Comment by aralroca** [comment]
I added this scripts:

- `npm run format:all` -> Format all files
- `npm run format` -> Format only these files that have changes from last commit
- `npm run lint:all` -> Lint all files
- `npm run lint` -> Lint only these files that have changes from last commit

Besides, as I have put husky, now whenever you make a commit a reformat of the commit files will be done.

**Comment by KovDimaY** [comment]
Great job, @aralroca! Thank you! I just realized I do not have even linter in this project! Probably later in the future I will add and configure it the way I used to work in my other projects... 🤔

**Review by KovDimaY — APPROVED** [review]
Great job, thank you for your contribution! 👍

**Pull request merged**
